{
  "totalNumberSkippingTests": 3,
  "bugType": "passing_passing",
  "totalNumberErroringTests": 8,
  "repo": "square/retrofit",
  "metrics": {
    "FailureNames": [
      "rx.exceptions.OnCompletedFailedException",
      "rx.exceptions.OnErrorFailedException",
      "java.lang.AssertionError"
    ],
    "StepsDurationsInSeconds": {
      "CheckoutBuggyBuildSourceCode": 0,
      "ComputeClasspath": 1,
      "ComputeTestDir": 0,
      "GatherTestInformationPreviousBuildSourceCode": 0,
      "ResolveDependency": 71,
      "BuildProjectBuild": 22,
      "BuildProjectPreviousBuildSourceCode": 82,
      "TestProjectBuild": 26,
      "ComputeSourceDir": 1,
      "InitRepoToPush": 1,
      "TestProjectPreviousBuildSourceCode": 32,
      "GatherTestInformationBuild": 0,
      "CloneRepository": 8,
      "CheckoutPatchedBuild": 0,
      "NopolRepair": 6,
      "PushIncriminatedBuild": 3,
      "CommitPatch": 3
    },
    "NbFailingTests": 9,
    "BugCommitUrl": "http://github.com/square/retrofit/commit/f35914b3010b909fb9c490f1a67819409fc8a303",
    "PatchCommitUrl": "http://github.com/square/retrofit/commit/a2ca2aa4fc49518ed93403cdae1dbad7a5045be1",
    "ReproductionDate": "Jun 1, 2017 11:27:34 AM",
    "BuggyBuildId": 231764479,
    "PatchedBuilId": 231765304,
    "BuggyBuildURL": "http://travis-ci.org/square/retrofit/builds/231764479",
    "PatchedBuildURL": "http://travis-ci.org/square/retrofit/builds/231765304",
    "BuggyBuildDate": "May 13, 2017 2:45:17 AM",
    "PatchedBuildDate": "May 13, 2017 2:51:34 AM",
    "BugCommit": "f35914b3010b909fb9c490f1a67819409fc8a303",
    "PatchCommit": "a2ca2aa4fc49518ed93403cdae1dbad7a5045be1",
    "PatchChangedFiles": 3,
    "PatchAddedLines": 0,
    "PatchDeletedLines": 0,
    "NbRunningTests": 377,
    "NbLibraries": 11,
    "NbFileApp": 238,
    "NbFileTests": 170,
    "NbCPU": 56,
    "FreeMemory": 1129954008,
    "TotalMemory": 1521483776,
    "AngelicValuesByTest": {
      "retrofit2/adapter/rxjava/AsyncTest": 0,
      "retrofit2/adapter/rxjava/CompletableThrowingSafeSubscriberTest": 0,
      "retrofit2/adapter/rxjava/ObservableThrowingSafeSubscriberTest": 0
    },
    "FreeMemoryByStep": {
      "CheckoutBuggyBuildSourceCode": 1186916424,
      "ComputeClasspath": 1045386320,
      "ComputeTestDir": 1197665928,
      "GatherTestInformationPreviousBuildSourceCode": 1124209680,
      "ResolveDependency": 1174373928,
      "BuildProjectBuild": 1314581640,
      "BuildProjectPreviousBuildSourceCode": 1154663664,
      "TestProjectBuild": 1306903688,
      "ComputeSourceDir": 1208413864,
      "InitRepoToPush": 1048969008,
      "TestProjectPreviousBuildSourceCode": 1145705536,
      "GatherTestInformationBuild": 1299125576,
      "CloneRepository": 1251405768,
      "CheckoutPatchedBuild": 1341453808,
      "NopolRepair": 1388127480,
      "PushIncriminatedBuild": 1168752416,
      "CommitPatch": 1129954008
    }
  },
  "bugCommit": "https://github.com/square/retrofit/compare/85593d29acbb...f35914b3010b",
  "failingModule": "/root/workspace/square/retrofit/231764479/retrofit-adapters/rxjava",
  "hostname": "spirals-spoon3r",
  "totalNumberFailingTests": 1,
  "error-types": [
    "rx.exceptions.OnCompletedFailedException",
    "rx.exceptions.OnErrorFailedException",
    "java.lang.AssertionError"
  ],
  "totalNumberRunningTests": 377,
  "failing-test-cases": [
    {
      "className": "retrofit2.adapter.rxjava.AsyncTest",
      "failingMethods": [
        "retrofit2.adapter.rxjava.AsyncTest#bodyThrowingInOnSafeSubscriberErrorDeliveredToPlugin"
      ],
      "erroringMethods": [],
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "isError": false
        }
      ],
      "nbFailures": 1,
      "nbErrors": 0
    },
    {
      "className": "retrofit2.adapter.rxjava.CompletableThrowingSafeSubscriberTest",
      "failingMethods": [],
      "erroringMethods": [
        "retrofit2.adapter.rxjava.CompletableThrowingSafeSubscriberTest#bodyThrowingInOnErrorDeliveredToPlugin",
        "retrofit2.adapter.rxjava.CompletableThrowingSafeSubscriberTest#throwingInOnCompleteDeliveredToPlugin"
      ],
      "failures": [
        {
          "failureName": "rx.exceptions.OnCompletedFailedException",
          "failureDetail": "java.lang.RuntimeException",
          "isError": true
        },
        {
          "failureName": "rx.exceptions.OnErrorFailedException",
          "failureDetail": "2 exceptions occurred. ",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest",
      "failingMethods": [],
      "erroringMethods": [
        "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest#resultThrowingInOnErrorDeliveredToPlugin",
        "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest#responseThrowingInOnCompleteDeliveredToPlugin",
        "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest#resultThrowingInOnCompletedDeliveredToPlugin",
        "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest#responseThrowingInOnErrorDeliveredToPlugin",
        "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest#bodyThrowingInOnErrorDeliveredToPlugin",
        "retrofit2.adapter.rxjava.ObservableThrowingSafeSubscriberTest#bodyThrowingInOnCompleteDeliveredToPlugin"
      ],
      "failures": [
        {
          "failureName": "rx.exceptions.OnErrorFailedException",
          "failureDetail": "Error occurred when trying to propagate error to Observer.onError",
          "isError": true
        },
        {
          "failureName": "rx.exceptions.OnErrorFailedException",
          "failureDetail": "Error occurred when trying to propagate error to Observer.onError",
          "isError": true
        },
        {
          "failureName": "rx.exceptions.OnCompletedFailedException",
          "isError": true
        },
        {
          "failureName": "rx.exceptions.OnCompletedFailedException",
          "isError": true
        },
        {
          "failureName": "rx.exceptions.OnErrorFailedException",
          "failureDetail": "Error occurred when trying to propagate error to Observer.onError",
          "isError": true
        },
        {
          "failureName": "rx.exceptions.OnCompletedFailedException",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    }
  ]
}