nopolinfo #0
location: FailureLocation{className='org.assertj.core.api.throwable.ThrowableAssert_hasCause_Test', failingMethods=[org.assertj.core.api.throwable.ThrowableAssert_hasCause_Test#should_fail_if_actual_and_expected_cause_have_different_types], erroringMethods=[], failures=[FailureType{failureName='java.lang.AssertionError', failureDetail='
Expected: (an instance of java.lang.AssertionError and exception with message "\nExpecting a cause with type:\n  <\"java.lang.NullPointerException\">\nbut type was:\n  <\"java.lang.IllegalStateException\">.")
     but: exception with message "\nExpecting a cause with type:\n  <\"java.lang.NullPointerException\">\nbut type was:\n  <\"java.lang.IllegalStateException\">." message was "\nExpecting a cause with type:\n  <\"java.lang.IllegalStateException\">\nbut type was:\n  <\"java.lang.NullPointerException\">."
Stacktrace was: java.lang.AssertionError: 
Expecting a cause with type:
  <"java.lang.IllegalStateException">
but type was:
  <"java.lang.NullPointerException">.
 at org.assertj.core.internal.Failures.failure(Failures.java:111)
 at org.assertj.core.internal.Throwables.assertHasCause(Throwables.java:86)
 at org.assertj.core.api.AbstractThrowableAssert.hasCause(AbstractThrowableAssert.java:111)
 at org.assertj.core.api.throwable.ThrowableAssert_hasCause_Test.should_fail_if_actual_and_expected_cause_have_different_types(ThrowableAssert_hasCause_Test.java:49)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
 at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
 at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
 at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
', isError=false}], nbFailures=1, nbErrors=0}
status: NOPATCH
dateEnd: Thu May 18 10:43:15 CEST 2017
allocatedtime: 120minutes 
passingTime: 0minutes 
nb patches: 0
nopol context: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=false, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=COND_THEN_PRE, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='./z3_for_linux', projectSources=[./workspace/joel-costigliola/assertj-core/190735366/src/main/java, /root/./workspace/joel-costigliola/assertj-core/190735366/src/main/java], projectClasspath='[Ljava.net.URL;@6c451c9c', projectTests=[org.assertj.core.api.throwable.ThrowableAssert_hasCause_Test], complianceLevel=8, outputFolder=null, json=false}
exception: null
nbStatements: 0
nbAngelicValues: 0
ignoreStatus: NOTHING_TO_IGNORE
----------



