{
  "totalNumberSkippingTests": 6,
  "bugType": "passing_passing",
  "totalNumberErroringTests": 1,
  "repo": "joel-costigliola/assertj-core",
  "bugCommit": "https://github.com/joel-costigliola/assertj-core/compare/a7bb8b243d1c...7b1a9d81b5c9",
  "failingModule": "/root/workspace/joel-costigliola/assertj-core/192215786",
  "hostname": "spirals-vortex.lille.inria.fr",
  "totalNumberFailingTests": 0,
  "error-types": [
    "org.assertj.core.util.introspection.IntrospectionError"
  ],
  "totalNumberRunningTests": 9615,
  "failing-test-cases": [
    {
      "className": "org.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test#should_be_able_to_extract_values_returned_from_default_methods_from_given_iterable_elements"
      ],
      "failures": [
        {
          "failureName": "org.assertj.core.util.introspection.IntrospectionError",
          "failureDetail": "\nCan\u0027t find any field or property with name \u0027name\u0027.\nError when introspecting properties was :\n- No getter for property \u0027name\u0027 in org.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test$Person \nError when introspecting fields was :\n- Unable to obtain the value of the field \u003c\u0027name\u0027\u003e from \u003corg.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test$Person@34b87182\u003e",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    }
  ]
}