nopolinfo #0
location: FailureLocation{className='com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest', failingMethods=[com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest#qualifiedMethod, com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest#innerClassTypeQualifier, com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest#testReadWriteLockCopy, com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest#tryWithResources, com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest#qualfiedType, com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest#testUnheldItselfGuard], erroringMethods=[], failures=[FailureType{failureName='skipped', failureDetail='skipped', isError=false}, FailureType{failureName='skipped', failureDetail='skipped', isError=false}, FailureType{failureName='skipped', failureDetail='skipped', isError=false}, FailureType{failureName='skipped', failureDetail='b/26834754', isError=false}, FailureType{failureName='java.lang.AssertionError', failureDetail='Did not see an error on line 9 matching . All errors:
[]', isError=false}, FailureType{failureName='skipped', failureDetail='b/26834754', isError=false}], nbFailures=6, nbErrors=0}
status: NOPATCH
dateEnd: Thu May 18 10:56:28 CEST 2017
allocatedtime: 120minutes 
passingTime: 0minutes 
nb patches: 0
nopol context: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=false, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=COND_THEN_PRE, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='./z3_for_linux', projectSources=[./workspace/google/error-prone/190790158/check_api/src/main/java, /root/./workspace/google/error-prone/190790158/check_api/src/main/java, ./workspace/google/error-prone/190790158/test_helpers/src/main/java, /root/./workspace/google/error-prone/190790158/test_helpers/src/main/java, ./workspace/google/error-prone/190790158/core/src/main/java, /root/./workspace/google/error-prone/190790158/core/src/main/java, ./workspace/google/error-prone/190790158/annotation/src/main/java, /root/./workspace/google/error-prone/190790158/annotation/src/main/java, ./workspace/google/error-prone/190790158/annotations/src/main/java, /root/./workspace/google/error-prone/190790158/annotations/src/main/java, ./workspace/google/error-prone/190790158/docgen/src/main/java, /root/./workspace/google/error-prone/190790158/docgen/src/main/java, ./workspace/google/error-prone/190790158/docgen_processor/src/main/java, /root/./workspace/google/error-prone/190790158/docgen_processor/src/main/java, ./workspace/google/error-prone/190790158/ant/src/main/java, /root/./workspace/google/error-prone/190790158/ant/src/main/java, ./workspace/google/error-prone/190790158/refaster/src/main/java, /root/./workspace/google/error-prone/190790158/refaster/src/main/java], projectClasspath='[Ljava.net.URL;@6f0628de', projectTests=[com.google.errorprone.bugpatterns.threadsafety.GuardedByCheckerTest], complianceLevel=8, outputFolder=null, json=false}
exception: null
nbStatements: 0
nbAngelicValues: 0
ignoreStatus: NOTHING_TO_IGNORE
----------



nopolinfo #1
location: FailureLocation{className='com.google.errorprone.bugpatterns.CheckReturnValueTest', failingMethods=[com.google.errorprone.bugpatterns.CheckReturnValueTest#testPositiveCases, com.google.errorprone.bugpatterns.CheckReturnValueTest#ignoreInTestsWithRule], erroringMethods=[], failures=[FailureType{failureName='java.lang.AssertionError', failureDetail='Saw unexpected error on line 5. All errors:
[/Test.java:5: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    foo.f();
         ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?]', isError=false}, FailureType{failureName='java.lang.AssertionError', failureDetail='Saw unexpected error on line 59. All errors:
[/com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:37: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    increment(i);
             ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:43: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    this.intValue.increment();
                           ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean 'this.intValue = this.intValue.increment();'?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:49: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    value.increment();
                   ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean 'value = value.increment();'?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:54: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    new IntValue(1).increment();
                             ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:57: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    new IntValue(1).increment();
                             ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:59: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    new IntValue(1).increment(); // No error here, last statement in block
                             ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:113: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
      this.increment();
                    ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:118: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
     increment();
              ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?, /com/google/errorprone/bugpatterns/CheckReturnValuePositiveCases.java:137: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
      lb1();
         ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?]', isError=false}], nbFailures=2, nbErrors=0}
status: NOPATCH
dateEnd: Thu May 18 10:56:40 CEST 2017
allocatedtime: 120minutes 
passingTime: 0minutes 
nb patches: 0
nopol context: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=false, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=COND_THEN_PRE, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='./z3_for_linux', projectSources=[./workspace/google/error-prone/190790158/check_api/src/main/java, /root/./workspace/google/error-prone/190790158/check_api/src/main/java, ./workspace/google/error-prone/190790158/test_helpers/src/main/java, /root/./workspace/google/error-prone/190790158/test_helpers/src/main/java, ./workspace/google/error-prone/190790158/core/src/main/java, /root/./workspace/google/error-prone/190790158/core/src/main/java, ./workspace/google/error-prone/190790158/annotation/src/main/java, /root/./workspace/google/error-prone/190790158/annotation/src/main/java, ./workspace/google/error-prone/190790158/annotations/src/main/java, /root/./workspace/google/error-prone/190790158/annotations/src/main/java, ./workspace/google/error-prone/190790158/docgen/src/main/java, /root/./workspace/google/error-prone/190790158/docgen/src/main/java, ./workspace/google/error-prone/190790158/docgen_processor/src/main/java, /root/./workspace/google/error-prone/190790158/docgen_processor/src/main/java, ./workspace/google/error-prone/190790158/ant/src/main/java, /root/./workspace/google/error-prone/190790158/ant/src/main/java, ./workspace/google/error-prone/190790158/refaster/src/main/java, /root/./workspace/google/error-prone/190790158/refaster/src/main/java], projectClasspath='[Ljava.net.URL;@35dc849b', projectTests=[com.google.errorprone.bugpatterns.CheckReturnValueTest], complianceLevel=8, outputFolder=null, json=false}
exception: null
nbStatements: 0
nbAngelicValues: 0
ignoreStatus: NOTHING_TO_IGNORE
----------



nopolinfo #2
location: FailureLocation{className='com.google.errorprone.bugpatterns.MustBeClosedCheckerTest', failingMethods=[com.google.errorprone.bugpatterns.MustBeClosedCheckerTest#negativeCase], erroringMethods=[], failures=[FailureType{failureName='java.lang.AssertionError', failureDetail='Saw unexpected error on line 80. All errors:
[/com/google/errorprone/bugpatterns/MustBeClosedCheckerNegativeCases.java:80: error: [MustBeClosedChecker] Constructor must be called within the resource variable initializer of a try-with-resources statement.
    return new MustBeClosedAnnotatedConstructor();
           ^
    (see http://errorprone.info/bugpattern/MustBeClosedChecker), /com/google/errorprone/bugpatterns/MustBeClosedCheckerNegativeCases.java:86: error: [MustBeClosedChecker] mustBeClosedAnnotatedMethod must be called within the resource variable initializer of a try-with-resources statement.
    return new Foo().mustBeClosedAnnotatedMethod();
                                                ^
    (see http://errorprone.info/bugpattern/MustBeClosedChecker)]', isError=false}], nbFailures=1, nbErrors=0}
status: NOPATCH
dateEnd: Thu May 18 10:56:52 CEST 2017
allocatedtime: 120minutes 
passingTime: 0minutes 
nb patches: 0
nopol context: Config{synthesisDepth=3, collectStaticMethods=true, collectStaticFields=false, collectLiterals=false, onlyOneSynthesisResult=false, sortExpressions=true, maxLineInvocationPerTest=250, timeoutMethodInvocation=2000, dataCollectionTimeoutInSecondForSynthesis=900, addWeight=0.19478, subWeight=0.04554, mulWeight=0.0102, divWeight=0.00613, andWeight=0.10597, orWeight=0.05708, eqWeight=0.22798, nEqWeight=0.0, lessEqWeight=0.0255, lessWeight=0.0947, methodCallWeight=0.1, fieldAccessWeight=0.08099, constantWeight=0.14232, variableWeight=0.05195, mode=REPAIR, type=COND_THEN_PRE, synthesis=DYNAMOTH, oracle=ANGELIC, solver=Z3, solverPath='./z3_for_linux', projectSources=[./workspace/google/error-prone/190790158/check_api/src/main/java, /root/./workspace/google/error-prone/190790158/check_api/src/main/java, ./workspace/google/error-prone/190790158/test_helpers/src/main/java, /root/./workspace/google/error-prone/190790158/test_helpers/src/main/java, ./workspace/google/error-prone/190790158/core/src/main/java, /root/./workspace/google/error-prone/190790158/core/src/main/java, ./workspace/google/error-prone/190790158/annotation/src/main/java, /root/./workspace/google/error-prone/190790158/annotation/src/main/java, ./workspace/google/error-prone/190790158/annotations/src/main/java, /root/./workspace/google/error-prone/190790158/annotations/src/main/java, ./workspace/google/error-prone/190790158/docgen/src/main/java, /root/./workspace/google/error-prone/190790158/docgen/src/main/java, ./workspace/google/error-prone/190790158/docgen_processor/src/main/java, /root/./workspace/google/error-prone/190790158/docgen_processor/src/main/java, ./workspace/google/error-prone/190790158/ant/src/main/java, /root/./workspace/google/error-prone/190790158/ant/src/main/java, ./workspace/google/error-prone/190790158/refaster/src/main/java, /root/./workspace/google/error-prone/190790158/refaster/src/main/java], projectClasspath='[Ljava.net.URL;@1c1bb1e7', projectTests=[com.google.errorprone.bugpatterns.MustBeClosedCheckerTest], complianceLevel=8, outputFolder=null, json=false}
exception: null
nbStatements: 0
nbAngelicValues: 0
ignoreStatus: NOTHING_TO_IGNORE
----------



