{
  "totalNumberSkippingTests": 17,
  "bugType": "passing_passing",
  "totalNumberErroringTests": 0,
  "repo": "google/error-prone",
  "metrics": {
    "FailureNames": [
      "java.lang.AssertionError"
    ],
    "StepsDurationsInSeconds": {
      "CheckoutBuggyBuildSourceCode": 0,
      "ComputeClasspath": 1,
      "ComputeTestDir": 0,
      "GatherTestInformationPreviousBuildSourceCode": 0,
      "ResolveDependency": 25,
      "BuildProjectBuild": 15,
      "BuildProjectPreviousBuildSourceCode": 23,
      "TestProjectBuild": 368,
      "ComputeSourceDir": 0,
      "InitRepoToPush": 6,
      "TestProjectPreviousBuildSourceCode": 369,
      "GatherTestInformationBuild": 0,
      "CloneRepository": 45,
      "CheckoutPatchedBuild": 0,
      "NopolRepair": 29,
      "PushIncriminatedBuild": 4,
      "CommitPatch": 5
    },
    "NbFailingTests": 2,
    "BugCommitUrl": "http://github.com/google/error-prone/commit/f6a5928cf5f748028e17ab0fbbffbe55c955881e",
    "PatchCommitUrl": "http://github.com/google/error-prone/commit/87670d7a1fb74ab51260c81f946c4c23e5a96ede",
    "ReproductionDate": "May 9, 2017 10:12:13 PM",
    "BuggyBuildId": 211456623,
    "PatchedBuilId": 211897436,
    "BuggyBuildURL": "http://travis-ci.org/google/error-prone/builds/211456623",
    "PatchedBuildURL": "http://travis-ci.org/google/error-prone/builds/211897436",
    "BuggyBuildDate": "Mar 15, 2017 7:17:02 PM",
    "PatchedBuildDate": "Mar 16, 2017 9:35:16 PM",
    "BugCommit": "f6a5928cf5f748028e17ab0fbbffbe55c955881e",
    "PatchCommit": "87670d7a1fb74ab51260c81f946c4c23e5a96ede",
    "PatchChangedFiles": 4,
    "PatchAddedLines": 0,
    "PatchDeletedLines": 0,
    "NbRunningTests": 2040,
    "NbLibraries": 53,
    "NbFileApp": 1056,
    "NbFileTests": 1458,
    "NbCPU": 56,
    "FreeMemory": 2464613704,
    "TotalMemory": 3894935552,
    "AngelicValuesByTest": {
      "com/google/errorprone/bugpatterns/RestrictedApiCheckerTest": 0,
      "com/google/errorprone/bugpatterns/JUnit4TestNotRunTest": 0
    },
    "FreeMemoryByStep": {
      "CheckoutBuggyBuildSourceCode": 1169059280,
      "ComputeClasspath": 1404883168,
      "ComputeTestDir": 1218454304,
      "GatherTestInformationPreviousBuildSourceCode": 1038688656,
      "ResolveDependency": 1143766344,
      "BuildProjectBuild": 3159975128,
      "BuildProjectPreviousBuildSourceCode": 1126834272,
      "TestProjectBuild": 3141308744,
      "ComputeSourceDir": 1230778648,
      "InitRepoToPush": 1409032064,
      "TestProjectPreviousBuildSourceCode": 1076035488,
      "GatherTestInformationBuild": 3111502880,
      "CloneRepository": 1291032208,
      "CheckoutPatchedBuild": 3177224296,
      "NopolRepair": 1521471304,
      "PushIncriminatedBuild": 2621818928,
      "CommitPatch": 2464613704
    }
  },
  "bugCommit": "https://github.com/google/error-prone/compare/26abc94386b9...f6a5928cf5f7",
  "failingModule": "/root/workspace/google/error-prone/211456623/core",
  "hostname": "spirals-spoon3r",
  "totalNumberFailingTests": 2,
  "error-types": [
    "java.lang.AssertionError"
  ],
  "totalNumberRunningTests": 2040,
  "failing-test-cases": [
    {
      "className": "com.google.errorprone.bugpatterns.RestrictedApiCheckerTest",
      "failingMethods": [
        "com.google.errorprone.bugpatterns.RestrictedApiCheckerTest#testAllowAllDefintionsInFile"
      ],
      "erroringMethods": [],
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "failureDetail": "Saw unexpected error on line 11. All errors:\n[/Testcase.java:11: error: [RestrictedApi] test\n     restrictedMethod();\n                     ^\n    (see foo)]",
          "isError": false
        }
      ],
      "nbFailures": 1,
      "nbErrors": 0
    },
    {
      "className": "com.google.errorprone.bugpatterns.JUnit4TestNotRunTest",
      "failingMethods": [
        "com.google.errorprone.bugpatterns.JUnit4TestNotRunTest#shouldNotDetectMethodsOnAbstractClass"
      ],
      "erroringMethods": [],
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "failureDetail": "Saw unexpected error on line 5. All errors:\n[/Test.java:5: error: [JUnit4TestNotRun] Test method will not be run; please add @Test annotation\n  public void testDoSomething() {}\n              ^\n    (see http://errorprone.info/bugpattern/JUnit4TestNotRun)\n  Did you mean \u0027@Test\u0027?]",
          "isError": false
        }
      ],
      "nbFailures": 1,
      "nbErrors": 0
    }
  ]
}