{
  "totalNumberSkippingTests": 4,
  "bugType": "passing_passing",
  "totalNumberErroringTests": 0,
  "repo": "square/retrofit",
  "bugCommit": "https://github.com/square/retrofit/compare/522592bb11fc...9d621ff8c512",
  "failingModule": "/root/workspace/square/retrofit/230461355/retrofit-mock",
  "hostname": "spirals-vortex.lille.inria.fr",
  "totalNumberFailingTests": 1,
  "error-types": [
    "java.lang.AssertionError"
  ],
  "totalNumberRunningTests": 526,
  "failing-test-cases": [
    {
      "className": "retrofit2.mock.NetworkBehaviorTest",
      "failingMethods": [
        "retrofit2.mock.NetworkBehaviorTest#defaultThrowable"
      ],
      "erroringMethods": [],
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "failureDetail": " Expecting:  \u003cjava.io.IOException: Mock failure!\u003e to be exactly an instance of:  \u003cretrofit2.mock.MockRetrofitIOException\u003e but was an instance of:  \u003cjava.io.IOException\u003e",
          "isError": false
        }
      ],
      "nbFailures": 1,
      "nbErrors": 0
    }
  ]
}